server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: customer
  config:
    import: "optional:configserver:http://localhost:8010/"