server:
  port: 8081
spring:
  application:
    name: fraud
  config:
    import: "optional:configserver:http://localhost:8010/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka