auth:
  server:
    host: http://localhost:8080
spring:
  cloud:
    gateway:
      routes:
        - id: customer-requests
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**