jwt:
  secret: secret-phrase
spring:
  cloud:
    gateway:
      routes:
        - id: customer-authorized-requests
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
            - Header=Authorization, Bearer (.*)
          filters: AuthorizationHeaderFilter