jwt:
  secret: secret-phrase
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/customers
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: customers-app-client
            client-secret: xwI25p0BwK5hgP8EpdVhnTlXq975uKKG
            scope: openid
        provider:
          keycloak:
            token-uri: http://keycloak:8080/auth/realms/customers/protocol/openid-connect/token
openfeign:
  security:
    enabled: true
    client-registration-id: keycloak
management:
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      fraud:
        failureRateThreshold: 50
        registerHealthIndicator: true
    circuit-breaker-aspect-order: 1
  retry:
    retry-aspect-order: 2
    instances:
      fraud:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2